export type DayItem = {
  week: 1|2|3|4
  day: number
  title: string
  coding: string[]
  theory: string[]
  mini: string[]
  tags: string[]
}

const plan: DayItem[] = [
  {week:1, day:1, title:"Day 1 – var/let/const, scope, hoisting",
    coding:["Reverse string","Find max in array"],
    theory:["var vs let vs const","What is hoisting?"],
    mini:["Palindrome checker"],
    tags:["JS","Scope","Hoisting"]},
  {week:1, day:2, title:"Day 2 – Functions, closures, IIFE",
    coding:["Fibonacci sequence","Factorial"],
    theory:["What is closure?","When is it useful?"],
    mini:["Counter using closure"],
    tags:["Functions","Closures","IIFE"]},
  {week:1, day:3, title:"Day 3 – Prototypes, this, call/apply/bind",
    coding:["Flatten nested array","Deep clone object"],
    theory:["Difference between == and ===","Explain this"],
    mini:["Custom bind implementation"],
    tags:["Prototypes","this","bind"]},
  {week:1, day:4, title:"Day 4 – Classes & inheritance",
    coding:["Merge two sorted arrays","Remove duplicates"],
    theory:["Class vs prototype inheritance"],
    mini:["Shape → Circle & Rectangle"],
    tags:["Classes","Inheritance"]},
  {week:1, day:5, title:"Day 5 – Promises, async/await",
    coding:["Retry async function","Sequential vs parallel promises"],
    theory:["Explain the event loop"],
    mini:["Implement delay(ms) with promise"],
    tags:["Promises","Async/Await"]},
  {week:1, day:6, title:"Day 6 – Event loop, microtask vs macrotask",
    coding:["Debounce","Throttle"],
    theory:["Difference between process.nextTick and setImmediate"],
    mini:["Debounced search input"],
    tags:["Event loop","Performance"]},
  {week:1, day:7, title:"Day 7 – Review + Mock",
    coding:["Solve 5–6 JS problems"],
    theory:["Revise closures, async/await, inheritance","Mock Q&A"],
    mini:["—"],
    tags:["Review","Mock"]},
  {week:2, day:8, title:"Day 8 (React) – JSX, components, props/state",
    coding:["Counter app","Dynamic list rendering"],
    theory:["Functional vs class components"],
    mini:["Todo app with props"],
    tags:["React","JSX","State"]},
  {week:2, day:9, title:"Day 9 (React) – useEffect, useState, lifecycle",
    coding:["Timer app","API fetch"],
    theory:["How does React’s virtual DOM work?"],
    mini:["Weather app with API"],
    tags:["React","Hooks"]},
  {week:2, day:10, title:"Day 10 (Vue) – Directives (v-if, v-for, v-model)",
    coding:["Render list with v-for","Two-way binding"],
    theory:["Vue reactivity system"],
    mini:["Form validation"],
    tags:["Vue","Directives"]},
  {week:2, day:11, title:"Day 11 (Vue) – Components, props, events",
    coding:["Parent-child data flow","Emit event handling"],
    theory:["Computed vs watchers"],
    mini:["Shopping cart"],
    tags:["Vue","Components"]},
  {week:2, day:12, title:"Day 12 – Routing (React Router, Vue Router)",
    coding:["Navigation between pages","Protected route"],
    theory:["SPA vs MPA"],
    mini:["Blog app with routes"],
    tags:["Routing","SPA"]},
  {week:2, day:13, title:"Day 13 – State management (Redux, Vuex/Pinia)",
    coding:["Counter with Redux","Global state for todo"],
    theory:["Context API vs Redux"],
    mini:["Todo app with Redux/Vuex"],
    tags:["Redux","Pinia","Vuex"]},
  {week:2, day:14, title:"Day 14 – Project Day",
    coding:["Build same CRUD app in React & Vue"],
    theory:["—"], mini:["—"],
    tags:["Project","CRUD"]},
  {week:3, day:15, title:"Day 15 – Node basics (fs, path, modules)",
    coding:["Read/write JSON","Word count CLI"],
    theory:["CommonJS vs ES modules"],
    mini:["CLI word counter"],
    tags:["Node","Modules"]},
  {week:3, day:16, title:"Day 16 – Express basics, middleware",
    coding:["Simple API","Middleware logging"],
    theory:["Types of middleware"],
    mini:["Custom logger"],
    tags:["Express","Middleware"]},
  {week:3, day:17, title:"Day 17 – REST APIs with Express",
    coding:["CRUD API","Error handling"],
    theory:["REST vs GraphQL"],
    mini:["Build CRUD API with Express"],
    tags:["REST","GraphQL"]},
  {week:3, day:18, title:"Day 18 – MongoDB + Mongoose",
    coding:["User schema","CRUD ops"],
    theory:["SQL vs NoSQL"],
    mini:["User registration API"],
    tags:["MongoDB","Mongoose"]},
  {week:3, day:19, title:"Day 19 – Auth (JWT, bcrypt)",
    coding:["Password hashing","Token generation"],
    theory:["Session vs JWT authentication"],
    mini:["Secure API with JWT"],
    tags:["Auth","JWT","bcrypt"]},
  {week:3, day:20, title:"Day 20 – Error handling + validation",
    coding:["Central error handler","Input validation"],
    theory:["try/catch vs middleware"],
    mini:["Express validation middleware"],
    tags:["Validation","Errors"]},
  {week:3, day:21, title:"Day 21 – Project Day",
    coding:["Build Task Manager API (CRUD + Auth + MongoDB)"],
    theory:["—"], mini:["—"],
    tags:["Project","API"]},
  {week:4, day:22, title:"Day 22 (React) – Performance optimization",
    coding:["Memoized component","Expensive calc optimization"],
    theory:["React Fiber"],
    mini:["Large list rendering optimization"],
    tags:["React","Performance"]},
  {week:4, day:23, title:"Day 23 (Vue) – Performance optimization",
    coding:["Lazy load component","Optimize list rendering"],
    theory:["Vue vs React virtual DOM"],
    mini:["Image gallery optimization"],
    tags:["Vue","Performance"]},
  {week:4, day:24, title:"Day 24 (Node) – Streams & clustering",
    coding:["File streaming","Log reader"],
    theory:["Process vs thread in Node"],
    mini:["Stream a log file"],
    tags:["Node","Streams","Cluster"]},
  {week:4, day:25, title:"Day 25 – Caching & scaling APIs",
    coding:["Cache API response","Rate limiting"],
    theory:["CAP theorem basics"],
    mini:["Redis caching demo"],
    tags:["Caching","Scaling","Redis"]},
  {week:4, day:26, title:"Day 26 – Security (CORS, CSRF, XSS)",
    coding:["Validate user input","Secure headers"],
    theory:["Explain CORS flow"],
    mini:["Prevent XSS in input"],
    tags:["Security","CORS","XSS"]},
  {week:4, day:27, title:"Day 27 – System design basics",
    coding:["—"],
    theory:["Design Instagram feed API"],
    mini:["Sketch high-level architecture"],
    tags:["System Design"]},
  {week:4, day:28, title:"Day 28 – React Mock Interview",
    coding:["2 React coding tasks"],
    theory:["React hooks + optimization"],
    mini:["Mock session"],
    tags:["Mock","React"]},
  {week:4, day:29, title:"Day 29 – Vue + Node Mock Interview",
    coding:["2 Vue/Node problems"],
    theory:["Backend scaling, Vue internals"],
    mini:["Mock session"],
    tags:["Mock","Vue","Node"]},
  {week:4, day:30, title:"Day 30 – Final Full Mock (90 min)",
    coding:["2 JS + 1 React/Vue + 1 Node problem"],
    theory:["System design, async, performance"],
    mini:["Simulated real interview"],
    tags:["Final","Mock"]},
]

export default plan
